Repository modern-agile-team/Menbosha-back, pull requests merged in 2023-12, with the labels that each got.

#13 엔티티 통합 / chat빼고 수정완료
  src/boards/controllers/Boards.controller.ts
  src/boards/dto/boards.one.response.dto.ts
  src/boards/dto/boards.response.dto.ts
  src/boards/entities/help-me-board.entity.ts
  src/boards/entities/mentor-board-image.entity.ts
  src/boards/entities/mentor-board.entity.ts
  src/boards/repository/boards.repository.ts
  src/boards/services/Boards.service.ts
  src/comments/entities/help-you-comment.entity.ts
  src/common/entity/badge-list.entity.ts
  src/common/entity/category-list.entity.ts
  src/users/entities/user-badge.entity.ts
  src/users/entities/user-review.entity.ts
  src/users/entities/user.entity.ts
Labels: Setting

#20 change import name board image
  src/boards/boards.module.ts
  src/boards/dto/create.board-image.dto.ts
  src/boards/entities/help-me-board-image.entity.ts
  src/boards/repository/boardImage.repository.ts
  src/boards/services/BoardImage.service.ts
  src/config/typeorm.config.ts
  src/main.ts
Labels: Setting

#23 Feat/#22/mentor board api
  src/app.module.ts
  src/boards/controllers/Boards.controller.ts
  src/boards/dto/create.board.dto.ts
  src/boards/dto/create.mentor.board.dto.ts
  src/boards/entities/help-me-board.entity.ts
  src/boards/entities/mentor-board.entity.ts
  src/boards/repository/boards.repository.ts
  src/boards/services/Boards.service.ts
  src/common/entity/category-list.entity.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user.repository.ts
Labels: Bugfix, Modify

#27 Modify/#24/로그인 인터페이스 적용
  src/auth/controllers/auth.controller.ts
  src/auth/interfaces/auth-service.interface.ts
  src/auth/services/auth.service.ts
Labels: Refactor

#28 Feat/#22/mentor board api
  src/boards/boards.module.ts
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/controllers/mentor.board.controller.ts
  src/boards/dto/boards.one.response.dto.ts
  src/boards/dto/boards.response.dto.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/help.me.board.service.ts
  src/boards/services/mentor.board.service.ts
  src/search/services/search.service.ts
  src/users/entities/user.entity.ts
Labels: Setting, Refactor

#31 Feat/#29/구글 로그인 추가
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.ts
Labels: Feat

#39 chat logic 1st completion
  src/app.module.ts
  src/chat/controllers/chat.controller.ts
  src/chat/dto/aggregate-chat-rooms.dto.ts
  src/chat/dto/chat-images.dto.ts
  src/chat/dto/chat-rooms.dto.ts
  src/chat/dto/chats.dto.ts
  src/chat/dto/login-chat-rooms.dto.ts
  src/chat/dto/post-chat.dto.ts
  src/chat/dto/response-post-chat-dto.ts
  src/chat/events/events.gateway.ts
  src/chat/exceptions/websocket-exception.filter.ts
  src/chat/repositories/chat.repository.ts
  src/chat/schemas/chat-images.schemas.ts
  src/chat/schemas/chats.schemas.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/create-chat-image.decorators.ts
  src/chat/swagger-decorators/create-chat-room.decorator.ts
  src/chat/swagger-decorators/get-chat-notifications.decorator.ts
  src/chat/swagger-decorators/get-chat-unread-counts.decorator.ts
  src/chat/swagger-decorators/get-one-chat-room.decorator.ts
  src/common/s3/s3.service.ts
Labels: Modify

#42 Feat/#35/help me board api
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/controllers/mentor.board.controller.ts
  src/boards/dto/helpMeBoard/creare.help.me.board.dto.ts
  src/boards/dto/helpMeBoard/create.board-image.dto.ts
  src/boards/dto/helpMeBoard/one.response.help.me.board.dto.ts
  src/boards/dto/helpMeBoard/response.help.me.board.dto.ts
  src/boards/dto/helpMeBoard/update.help.me.board.dto.ts
  src/boards/dto/helpMeBoard/update.help.me.board.response.dto.ts
  src/boards/dto/mentorBoard/create.mentor.board.dto.ts
  src/boards/dto/mentorBoard/create.metnor.board.response.dto.ts
  src/boards/dto/mentorBoard/one.response.mentor.boards.dto.ts
  src/boards/dto/mentorBoard/response.mentor.boards.dto.ts
  src/boards/dto/mentorBoard/update.mentor.board.dto.ts
  src/boards/dto/mentorBoard/update.mentor.board.response.dto.ts
  src/boards/repository/boardImage.repository.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/BoardImage.service.ts
  src/boards/services/help.me.board.service.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/helpMeBoard/add-help-me-baord-images-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/add-help-me-board-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/delete-help-me-board-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/get-one-help-me-board.dtd.ts
  src/boards/swagger-decorators/helpMeBoard/get-page-help-me-board.decorator.ts
  src/boards/swagger-decorators/helpMeBoard/patch-help-me-board-images-decorators.ts
  src/boards/swagger-decorators/helpMeBoard/patch-help-me-board.decorator.ts
  src/boards/swagger-decorators/mentorBoard/add-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/delete-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-one-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-page-mentor-boards-decorators.ts
  src/boards/swagger-decorators/mentorBoard/patch-mentor-board-decorators.ts
  src/search/services/search.service.ts
  src/users/entities/user-intro.entity.ts
  src/users/entities/user.entity.ts
Labels: Modify

#44 Modify(#35) 오타 수정
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/swagger-decorators/helpMeBoard/get-one-help-me-board.dto.ts
  src/users/entities/user-intro.entity.ts
  src/users/entities/user.entity.ts
Labels: Refactor

#46 modify import route for ubuntu os
  src/chat/controllers/chat.controller.ts
Labels: Bugfix

#47 create search api
  src/common/interceptors/success-response.interceptor.ts
  src/search/controllers/search.controller.ts
  src/search/dtos/help-me-board-image.dto.ts
  src/search/dtos/search-all-boards-and-mentors-query.dto.ts
  src/search/dtos/search-all-help-me-board.dto.ts
  src/search/dtos/search-all-mentor.dto.ts
  src/search/dtos/search-all-page-size.dto.ts
  src/search/dtos/search-user-dto.ts
  src/search/repositories/search.repository.ts
  src/search/services/search.service.ts
  src/search/swagger-decorators/search-all-boards-and-mentors-for-page-size.swagger.ts
  src/search/swagger-decorators/search-all-boards-and-mentors.swagger.ts
  src/search/type/type.ts
  src/users/entities/user-intro.entity.ts
Labels: Feat

#51 fix(#50): google 로그인 에러 해결중
  src/auth/services/auth.service.ts
Labels: Bugfix

#49 fix(#30): dockerfile 수정
  dockerfile
Labels: Bugfix

#52 fix(#30): docker-compose 수정
  docker-compose.yml
Labels: Bugfix

#53 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#54 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#55 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#56 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#57 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#58 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#59 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#60 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#61 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#62 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#63 fix(#30): redis 테스트
  redis.conf
Labels: Bugfix

#64 fix(#30): redis설정 완
  docker-compose.yml
  dockerfile
  redis.conf
Labels: Deploy

#65 modify(#50): 개발용 토큰 만료시간 설정
  src/auth/services/token.service.ts
Labels: Modify

#66 bugfix(#50): google 토큰 발급 확인
  src/auth/services/auth.service.ts
Labels: Bugfix

#67 bugfix(#50): 구글 로그인 에러 테스트
  src/auth/services/auth.service.ts
Labels: Bugfix

#68 bugfix(#50): 구글 로그인 에러 테스트
  src/auth/services/auth.service.ts
Labels: Bugfix

#69 bugfix(#50): 구글 로그인 에러 고침
  src/auth/services/auth.service.ts
Labels: Bugfix

#72 Feat/#43/mentor list api
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/services/help.me.board.service.ts
  src/boards/swagger-decorators/helpMeBoard/get-board-page-number.decorator.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-mentor-list-decorator.ts
  src/users/swagger-decorators/get-mentor-page-decorator.ts
Labels: Feat

#73 refactor(#43) refactor description
  src/users/swagger-decorators/get-mentor-list-decorator.ts
Labels: Refactor

#75 Feat/#30/redis 액세스 토큰 재발급 redis 사용
  src/auth/controllers/auth.controller.ts
  src/auth/services/token.service.ts
  src/boards/boards.module.ts
  src/comments/comment.module.ts
  src/common/redis/redis.service.ts
  src/config/redis-options.constants.ts
Labels: Feat
