Repository modern-agile-team/Menbosha-back, pull requests merged in 2024-03, with the labels that each got.

#289 deploy(#255)github action .env
  .github/workflows/ma6-main.yml
Labels: Deploy, Setting

#287 Modify/#286/modify chat validation
  src/admins/banned-user/dtos/banned-user-page-query.dto.ts
  src/admins/banned-user/dtos/create-banned-user-body.dto.ts
  src/boards/dto/helpMeBoard/help-me-board-page-query.dto.ts
  src/boards/dto/mentorBoard/mentor-board-page-query.dto.ts
  src/chat/dto/post-chat.dto.ts
  src/mentors/dtos/mentor-list-page-query.dto.ts
  src/mentors/mentor-reviews/dtos/create-mentor-review-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review-page-query-dto.ts
  src/mentors/mentor-reviews/dtos/patch-update-mentor-review.dto.ts
  src/mentors/mentor-reviews/swagger-decorators/create-mentor-review.decorator.ts
  src/mentors/mentor-reviews/swagger-decorators/patch-update-mentor-review.decorator.ts
  src/reports/dto/report-page-query-dto.ts
Labels: Modify

#291 deploy/#290/상용 서버 환경 및 local 환경인지에 따라 코드 다르게 동작하도록 수정
  package.json
  src/app.module.ts
  src/chat/controllers/chat.controller.ts
  src/chat/events/events.gateway.ts
  src/chat/swagger-decorators/find-one-chat-room.decorator.ts
  src/config/swagger.ts
  src/config/typeorm.config.ts
  src/main.ts
Labels: Deploy, Setting

#297 bugfix/#295/bugfix
  src/auth/services/auth.service.ts
Labels: Bugfix

#299 deploy/#290/annotation
  src/config/swagger.ts
  src/main.ts
Labels: Deploy

#305 setting/#301/pr reminder test
  .github/workflows/send-pr-remind.yml
Labels: Setting

#302 deploy(#255) nginx.conf 변경
  nginx.conf
Labels: Deploy, Setting

#307 🚨 bugfix(#306): 회원가입 할 때 인트로 로우 만들도록 수정
  src/auth/services/auth.service.ts
  src/users/repositories/user-intro.repository.ts
  src/users/services/user-intro-service.ts
Labels: Bugfix

#313 Deploy/#255/https back
  nginx.conf
Labels: Deploy, Bugfix

#315 setting/#314/add allow origin in cors setting
  src/main.ts
Labels: Deploy, Setting

#298 ✏️ modify(#296): 리턴값 mentorBoardCount, reviewCount 추가
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/get-user-info-with-badge-and-count.dto.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-user-info.decorators.ts
Labels: Modify

#321 setting/#320/modiy cors origin setting in socket
  src/chat/events/events.gateway.ts
Labels: Setting

#332 setting/#331/modify web socket gateway's cors setting
  src/chat/events/events.gateway.ts
Labels: Deploy, Setting

#326 Modify/#325/add constrants
  src/admins/banned-user/constants/banned-user.constant.ts
  src/admins/banned-user/dtos/create-banned-user-body.dto.ts
  src/boards/constants/help-me-board/help-me-board-order-field.enum.ts
  src/boards/constants/help-me-board/help-me-board.constant.ts
  src/boards/constants/mentor-board/mentor-board-order-field.enum.ts
  src/boards/constants/mentor-board/mentor-board.constant.ts
  src/boards/dto/helpMeBoard/create.help.me.board.dto.ts
  src/boards/dto/helpMeBoard/help-me-board-page-query.dto.ts
  src/boards/dto/helpMeBoard/help-me-board.dto.ts
  src/boards/dto/helpMeBoard/update.help.me.board.dto.ts
  src/boards/dto/mentorBoard/create.mentor.board.dto.ts
  src/boards/dto/mentorBoard/mentor-board-page-query.dto.ts
  src/boards/dto/mentorBoard/mentor-board.dto.ts
  src/boards/dto/mentorBoard/update.mentor.board.dto.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/category/dto/category.dto.ts
  src/category/services/category.service.ts
  src/common/types/order-field-for-helper.type.ts
  src/entities/HelpMeBoard.ts
  src/entities/MentorBoard.ts
  src/mentors/dtos/mentor-list-page-query.dto.ts
  src/mentors/dtos/user-intro-response.dto.ts
  src/mentors/dtos/user-with-image-and-intro.dto.ts
  src/mentors/mentor-reviews/constants/mentor-review.constant.ts
  src/mentors/mentor-reviews/dtos/create-mentor-review-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review-page-query-dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/mentor-reviews/dtos/patch-update-mentor-review.dto.ts
  src/mentors/repositories/mentor.repository.ts
  src/migrations/__utils/util.ts
  src/reports/constants/report.constant.ts
  src/search/dtos/search-all-help-me-board.dto.ts
  src/search/dtos/search-all-mentor.dto.ts
  src/search/dtos/search-user-dto.ts
  src/users/constants/user.constant.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/get-my-intro.dto.ts
  src/users/dtos/update-user-intro-dto.ts
  src/users/dtos/user-info.dto.ts
Labels: Modify

#328 Modify/#327/modify create help you co
  src/boards/boards.module.ts
  src/boards/services/help.me.board.service.ts
  src/comments/comment.module.ts
  src/comments/controllers/comments.controller.ts
  src/comments/dto/help-you-comment.dto.ts
  src/comments/repository/comments.repository.ts
  src/comments/services/comments.services.ts
  src/comments/swagger-decorators/post-help-you-comment-decorator.ts
  src/users/repositories/user.repository.ts
  src/users/swagger-decorators/get-user-info.decorators.ts
Labels: Modify

#333 Bugfix/#294/fix delete board api
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/controllers/mentor.board.controller.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/help.me.board.service.ts
  src/boards/services/mentor-board-likes.service.ts
  src/boards/services/mentor.board.service.ts
  src/comments/comment.module.ts
  src/comments/services/comments.services.ts
Labels: Bugfix, Modify

#336 deploy/#335/서버 환경에 따라 mongo db uri 다르게 설정
  src/app.module.ts
Labels: Deploy, Setting

#337 bugfix/#294/delete duplicaetd imports
  src/boards/services/help.me.board.service.ts
  src/comments/comment.module.ts
Labels: Delete, Bugfix

#339 deploy/#336/modify workflow
  .github/workflows/ma6-main.yml
Labels: Deploy, Setting

#342 Deploy/#338/isolate server environmen
  src/entities/Badge.ts
  src/entities/BannedUser.ts
  src/entities/Category.ts
  src/entities/HelpMeBoard.ts
  src/entities/HelpMeBoardImage.ts
  src/entities/HelpYouComment.ts
  src/entities/MentorBoard.ts
  src/entities/MentorBoardImage.ts
  src/entities/MentorBoardLike.ts
  src/entities/MentorReview.ts
  src/entities/MentorReviewChecklistCount.ts
  src/entities/Migrations.ts
  src/entities/Report.ts
  src/entities/Token.ts
  src/entities/TotalCount.ts
  src/entities/User.ts
  src/entities/UserBadge.ts
  src/entities/UserImage.ts
  src/entities/UserIntro.ts
  src/entities/UserRanking.ts
  src/migrations/badge/1709815357848-badge.ts
  src/migrations/category/1709815316486-category.ts
Labels: Setting

#344 Setting/#343/mange env with config mod
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/controllers/auth.controller.ts
  src/auth/jwt/factories/jwt-module-options.factory.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/boards/boards.module.ts
  src/boards/services/BoardImage.service.ts
  src/bootstrap.service.ts
  src/chat/events/events.gateway.ts
  src/chat/services/chat.service.ts
  src/common/redis/constants/ttl.enum.ts
  src/common/redis/factories/cache-module-options.factory.ts
  src/common/redis/redis.module.ts
  src/common/redis/services/redis.service.ts
  src/common/s3/constants/s3-client.token.ts
  src/common/s3/s3.module.ts
  src/common/s3/services/s3.service.ts
  src/config/swagger.ts
  src/config/typeorm.config.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/core/app-config/services/app-config.service.ts
  src/core/core.module.ts
  src/core/mongoose/factories/mongoose-module-options.factory.ts
  src/core/type-orm/factories/type-orm-module-options.factory.ts
  src/http-exceptions/services/http-exception.service.ts
  src/main.ts
  src/users/services/user-image.service.ts
  src/users/user.module.ts
Labels: Deploy, Setting, Refactor

#347 setting/#309/create notification in slack for ci/cd notification
  .github/workflows/ma6-main.yml
  src/app.module.ts
Labels: Setting

#346 modify/#345/add error handling
  src/mentors/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
Labels: Modify

#348 merge to main
  .github/workflows/ma6-main.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/controllers/auth.controller.ts
  src/auth/jwt/factories/jwt-module-options.factory.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/boards/boards.module.ts
  src/boards/services/BoardImage.service.ts
  src/bootstrap.service.ts
  src/chat/events/events.gateway.ts
  src/chat/services/chat.service.ts
  src/common/redis/constants/ttl.enum.ts
  src/common/redis/factories/cache-module-options.factory.ts
  src/common/redis/redis.module.ts
  src/common/redis/services/redis.service.ts
  src/common/s3/constants/s3-client.token.ts
  src/common/s3/s3.module.ts
  src/common/s3/services/s3.service.ts
  src/config/swagger.ts
  src/config/typeorm.config.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/core/app-config/services/app-config.service.ts
  src/core/core.module.ts
  src/core/mongoose/factories/mongoose-module-options.factory.ts
  src/core/type-orm/factories/type-orm-module-options.factory.ts
  src/http-exceptions/services/http-exception.service.ts
  src/main.ts
  src/mentors/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/users/services/user-image.service.ts
  src/users/user.module.ts
Labels: Deploy

#351 setting/#309/modify env setting and git ignore
  .gitignore
  src/core/app-config/app-config.module.ts
Labels: Setting

#352 setting/#309/modify dotenv config
  src/config/typeorm.config.ts
Labels: Setting

#353 🚨 bugfix(#350): deleteTokens 메서드 delete account API 에서 사용
  .gitignore
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.ts
Labels: Bugfix

#357 modify/#356/modify socket cors
  src/chat/events/events.gateway.ts
Labels: Setting, Modify

#359 bugfix/#358/modify bug logic
  src/auth/services/auth.service.ts
Labels: Bugfix

#362 Feat/#360/modify chat logic
  src/auth/auth.module.ts
  src/auth/services/auth.service.ts
  src/chat/chat.module.ts
  src/chat/controllers/chat.controller.ts
  src/chat/services/chat.service.ts
Labels: Feat, Modify

#364 Setting/#363/match server and local docker-compose
  .gitignore
  docker-compose.yml
Labels: Setting

#365 Feat/#349/building a rank system
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/users/controllers/user.controller.ts
  src/users/repositories/user.repository.ts
  src/users/services/user-ranking.service.ts
  src/users/swagger-decorators/get-user-rank-decorator.ts
Labels: Feat

#370 refactor(#349)return type
  src/users/services/user-ranking.service.ts
Labels: Refactor

#372 Feat/#349/building a rank system
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/users/controllers/user.controller.ts
  src/users/repositories/user.repository.ts
  src/users/services/user-ranking.service.ts
  src/users/swagger-decorators/get-user-rank-decorator.ts
Labels: Deploy

#371 Modify/#354/use cookie to new token
  src/auth/jwt/jwt-auth.guard.ts
  src/auth/jwt/jwt.strategy.ts
  src/common/interceptors/cookie.interceptor.ts
Labels: Modify

#376 deploy/#375/modify cors origin setting
  src/bootstrap.service.ts
  src/chat/events/events.gateway.ts
Labels: Deploy, Setting

#377 Deploy/#368/development subdomain setting
  docker-compose.yml
  nginx.conf
Labels: Setting

#379 Setting/#378/modify image url length
  src/entities/HelpMeBoardImage.ts
  src/entities/MentorBoardImage.ts
  src/entities/UserImage.ts
  src/migrations/help-me-board/1709815610192-help-me-board-image.ts
  src/migrations/mentor-board/1709815530689-mentor-board-image.ts
  src/migrations/user/1709815441214-user-image.ts
Labels: Setting, Modify

#381 merge to main
  docker-compose.yml
  nginx.conf
  src/bootstrap.service.ts
  src/chat/events/events.gateway.ts
  src/entities/HelpMeBoardImage.ts
  src/entities/MentorBoardImage.ts
  src/entities/UserImage.ts
  src/migrations/help-me-board/1709815610192-help-me-board-image.ts
  src/migrations/mentor-board/1709815530689-mentor-board-image.ts
  src/migrations/user/1709815441214-user-image.ts
Labels: Deploy

#385 Modify/#384/modify borad pagination api
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
Labels: Modify

#386 merge to main
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
Labels: Modify

#387 Deploy/#380/automatic renewal of ssl
  dockerfile
  renew_ssl_cert.sh
Labels: Deploy, Setting
