Repository modern-agile-team/Menbosha-back, pull requests merged in 2024-02, with the labels that each got.

#181 modify(#180): 회원가입 시 멘토 리뷰 체크리스트 카운트 테이블 로우 생성
  src/auth/services/auth.service.ts
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/users/repositories/user-image.repository.ts
  src/users/repositories/user.repository.ts
Labels: Modify

#182 doc(#136): swagger authorization 지속옵션 추가
  src/config/swagger.ts
  src/total-count/swagger-decorators/counting.decorator.ts
Labels: Doc

#183 deploy(#30): docker-compose 파일 수정
  docker-compose.yml
Labels: Deploy

#179 Feat/#175/increase checklist count
  src/mentor-reviews/mentor-reviews.module.ts
  src/mentor-reviews/services/mentor-reviews.service.ts
  src/total-count/dtos/mentor-review-checklist-count.dto.ts
  src/total-count/entities/mentor-review-checklist-count.entity.ts
  src/total-count/repositories/mentor-review-checklist-count.repository.ts
  src/total-count/services/mentor-review-checklist-counts.service.ts
  src/total-count/total-count.module.ts
Labels: Feat, Modify

#186 Feat/#185/create custom validator
  src/common/decorators/validators/is-not-empty-object-and-all-false.decorator.ts
  src/mentor-reviews/dtos/create-mentor-review-request-body.dto.ts
Labels: Feat, Bugfix

#190 Doc/#188/deprecated api
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/controllers/mentor.board.controller.ts
  src/boards/swagger-decorators/helpMeBoard/get-board-page-number.decorator.ts
  src/boards/swagger-decorators/mentorBoard/get-page-number-mentor-board-decorator.ts
Labels: Doc

#192 deploy/#30/redis redis module 설정 수정
  package-lock.json
  package.json
  src/common/redis/redis.module.ts
Labels: Deploy

#195 Deploy/#194/redis error: users.acl 파일 사용
  docker-compose.yml
  dockerfile
  redis.conf
  src/common/redis/redis.module.ts
  src/common/redis/redis.service.ts
  src/config/redis-options.constants.ts
  users.acl
Labels: Deploy, Bugfix

#199 deploy(#194): users.acl 파일 수정
  users.acl
Labels: Deploy, Bugfix

#200 deploy(#194): users.acl 파일 원래대로
  users.acl
Labels: Deploy, Bugfix

#201 deploy(#194): users.acl 파일 수정
  users.acl
Labels: Deploy, Bugfix

#202 deploy(#194): users.acl 파일, docker-compose 수정
  docker-compose.yml
  users.acl
Labels: Deploy, Bugfix

#203 deploy(#194): docker-compose command, volumes 수정
  docker-compose.yml
Labels: Deploy, Bugfix

#193 Bugfix/#191/modify query
  src/boards/repository/help.me.board.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/help.me.board.service.ts
  src/boards/services/mentor.board.service.ts
Labels: Bugfix, Modify

#196 Doc/#189/modify mentor list api
  src/app.module.ts
  src/common/types/order-field-for-helper.type.ts
  src/config/type-orm/typeorm.config.ts
  src/helpers/query-builder.helper.ts
  src/mentors/constants/mentor-order-field.enum.ts
  src/mentors/controllers/mentors.controller.ts
  src/mentors/dtos/mentor-list-page-query.dto.ts
  src/mentors/dtos/mentors-pagination-response.dto.ts
  src/mentors/dtos/user-intro-response.dto.ts
  src/mentors/dtos/user-with-image-and-intro.dto.ts
  src/mentors/mentor-reviews/constants/mentor-review-order-field.enum.ts
  src/mentors/mentor-reviews/controllers/mentor-reviews.controller.ts
  src/mentors/mentor-reviews/dtos/create-mentor-review-checklist-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/create-mentor-review-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review-checklist.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review-page-query-dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-reviews-pagination-response.dto.ts
  src/mentors/mentor-reviews/dtos/patch-update-mentor-review.dto.ts
  src/mentors/mentor-reviews/entities/mentor-review.entity.ts
  src/mentors/mentor-reviews/mentor-review-checklist/entities/mentor-review-checklist.entity.ts
  src/mentors/mentor-reviews/mentor-review-checklist/mentor-review-checklist.module.ts
  src/mentors/mentor-reviews/mentor-review-checklist/repositories/mentor-review-checklists.repository.ts
  src/mentors/mentor-reviews/mentor-review-checklist/services/mentor-review-checklist.service.ts
  src/mentors/mentor-reviews/mentor-reviews.module.ts
  src/mentors/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/mentors/mentor-reviews/swagger-decorators/create-mentor-review.decorator.ts
  src/mentors/mentor-reviews/swagger-decorators/find-mentor-reviews.decorator.ts
  src/mentors/mentor-reviews/swagger-decorators/find-one-mentor-review.decorator.ts
  src/mentors/mentor-reviews/swagger-decorators/patch-update-mentor-review.decorator.ts
  src/mentors/mentor-reviews/swagger-decorators/remove-mentor-review.decorator.ts
  src/mentors/mentors.module.ts
  src/mentors/repositories/mentor.repository.ts
  src/mentors/services/mentors.service.ts
  src/mentors/swagger-decorators/find-all-mentors-and-count.decorator.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
Labels: Doc, Modify

#198 Modify/#197/modify_help_me_boards
  src/boards/controllers/help.me.boards.controller.ts
Labels: Modify

#204 deploy(#194): docker-compose command, 수정
  docker-compose.yml
  users.acl
Labels: Deploy, Bugfix

#207 deploy(#194): redis.conf 원래대로
  docker-compose.yml
  redis.conf
Labels: Deploy, Bugfix

#208 deploy(#194): redis 오류 해결
  docker-compose.yml
Labels: Deploy, Bugfix

#210 Bugfix/#209/mentor review count entity
  src/config/typeorm.config.ts
  src/migrations/1707370531264-UpdateMentorReviewChecklistCountSchema.ts
  src/total-count/entities/mentor-review-checklist-count.entity.ts
Labels: Bugfix, Modify

#212 ✅ bugfix(#194): redis rdb파일 지속성 설정 (볼륨 마운트)
  docker-compose.yml
Labels: Bugfix

#217 modify/#215/modify mentorReview/BoardCount type
  src/mentors/dtos/user-with-image-and-intro.dto.ts
  src/mentors/swagger-decorators/find-all-mentors-and-count.decorator.ts
Labels: Modify

#218 modify/#216/modify property name
  src/boards/dto/mentorBoard/mentor-board-pagination-response.dto.ts
Labels: Refactor

#222 Delete/#220/drop mentor review checklist
  src/config/typeorm.config.ts
  src/mentors/mentor-reviews/constants/mentor-review-order-field.enum.ts
  src/mentors/mentor-reviews/dtos/create-mentor-review-checklist-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review-checklist.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/mentor-reviews/dtos/patch-update-mentor-review.dto.ts
  src/mentors/mentor-reviews/entities/mentor-review.entity.ts
  src/mentors/mentor-reviews/mentor-review-checklist/entities/mentor-review-checklist.entity.ts
  src/mentors/mentor-reviews/mentor-review-checklist/mentor-review-checklist.module.ts
  src/mentors/mentor-reviews/mentor-review-checklist/repositories/mentor-review-checklists.repository.ts
  src/mentors/mentor-reviews/mentor-review-checklist/services/mentor-review-checklist.service.ts
  src/mentors/mentor-reviews/mentor-reviews.module.ts
  src/mentors/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/migrations/1706687627541-create-mentor-review-checklist-count-table.ts
  src/migrations/1707370531264-modify-mentor-review-checklist-count-created-at.ts
  src/migrations/1707822958189-drop-mentor-review-checklist-table.ts
  src/migrations/1707823007803-alter-mentor-review-table.ts
  src/migrations/1707839631749-add-updated-at-mentor-review-table.ts
  src/total-count/repositories/mentor-review-checklist-count.repository.ts
Labels: Modify

#225 Modify/#224/add column checklist
  src/mentors/mentor-reviews/dtos/create-mentor-review-checklist-request-body.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-review.dto.ts
  src/mentors/mentor-reviews/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/mentor-reviews/entities/mentor-review.entity.ts
  src/migrations/1707897149688-add-column-at-mentor-review-table.ts
  src/total-count/dtos/mentor-review-checklist-count.dto.ts
  src/total-count/entities/mentor-review-checklist-count.entity.ts
Labels: Modify

#226 Feat/#219/apply subscribers
  src/app.module.ts
  src/config/typeorm.config.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/subscribers/mentor-review-checklist-count.subscriber.ts
Labels: Refactor

#227 Revert "Feat/#219/apply subscribers"
  src/app.module.ts
  src/config/typeorm.config.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/subscribers/mentor-review-checklist-count.subscriber.ts
Labels: Delete

#228 refactor/#224/modify comment
  src/total-count/entities/mentor-review-checklist-count.entity.ts
Labels: Delete

#230 modify/#229/skip take --> offset limit
  src/mentors/repositories/mentor.repository.ts
Labels: Bugfix, Modify

#234 Feat/#214/badge api
  src/migrations/1707977815270-update-user-badge.ts
  src/users/controllers/user.controller.ts
  src/users/entities/user-badge.entity.ts
  src/users/repositories/user-badge.repository.ts
  src/users/services/user-badge.service.ts
  src/users/swagger-decorators/get-user-badges-decorator.ts
  src/users/user.module.ts
  tsconfig.json
Labels: Feat

#231 Feat/#219/apply subscribers
  src/config/typeorm.config.ts
  src/mentors/mentor-reviews/controllers/mentor-reviews.controller.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/mentors/mentor-reviews/swagger-decorators/delete-mentor-review.decorator.ts
  src/subscribers/mentor-review-checklist-count.subscriber.ts
  src/total-count/repositories/mentor-review-checklist-count.repository.ts
  src/total-count/services/mentor-review-checklist-counts.service.ts
Labels: Feat

#237 modify/#236/modify help you comments pagination api
  src/boards/repository/help.me.board.repository.ts
  src/boards/services/help.me.board.service.ts
Labels: Modify

#238 Doc/#187/modify chat swagger
  src/chat/events/events.gateway.ts
  src/chat/exceptions/filters/websocket-exception.filter.ts
  src/chat/exceptions/socket.exception.ts
  src/chat/services/chat.service.ts
Labels: Modify

#242 ♻️ Refactor/#213/count api transaction: change count API to subscriber
  src/boards/boards.module.ts
  src/boards/services/mentor-board-likes.service.ts
  src/comments/swagger-decorators/delete-comment-decorator.ts
  src/comments/swagger-decorators/post-help-you-comment-decorator.ts
  src/config/typeorm.config.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/subscribers/help-you-comment.subscriber.ts
  src/subscribers/mentor-board-like.subscriber.ts
  src/subscribers/mentor-board.subscriber.ts
  src/subscribers/mentor-review.subscriber.ts
  src/subscribers/user-badge.subscriber.ts
  src/total-count/controllers/total-count.controller.ts
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/total-count/swagger-decorators/counting.decorator.ts
  src/total-count/total-count.module.ts
Labels: Refactor

#245 Modify/#239/redis token: accessToken도 redis에 저장
  package-lock.json
  package.json
  src/auth/controllers/auth.controller.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/services/token.service.ts
  src/common/redis/redis.module.ts
  src/common/redis/redis.service.ts
  src/common/redis/ttl.enum.ts
Labels: Modify

#246 Refactor/#241/token signature
  src/auth/jwt/jwt.strategy.ts
  src/auth/services/token.service.ts
Labels: Refactor

#243 doc(#214) swagger문서 최적화
  src/users/swagger-decorators/get-user-badges-decorator.ts
Labels: Doc

#249 bugfix(#248): user 서비스에서 findUser 메서드 추가
  src/auth/services/auth.service.ts
  src/users/services/user.service.ts
Labels: Bugfix

#250 modify(#247): 토큰 불일치 시 토큰 삭제 기능 추가 (비정상적인 접근 시 강제 로그아웃)
  src/auth/jwt/jwt.strategy.ts
  src/common/redis/redis.service.ts
Labels: Modify

#252 Setting/#251/create report api
  src/admins/admins.module.ts
  src/admins/controllers/admins.controller.ts
  src/admins/entities/banned-user.entity.ts
  src/admins/services/admins.service.ts
  src/app.module.ts
  src/boards/entities/help-me-board.entity.ts
  src/boards/entities/mentor-board.entity.ts
  src/comments/entities/help-you-comment.entity.ts
  src/config/typeorm.config.ts
  src/migrations/1708423002121-soft-delete-user.ts
  src/migrations/1708424573050-create-report-table.ts
  src/migrations/1708426630668-create-banned-user-table.ts
  src/migrations/1708479086561-boards-soft-delete.ts
  src/migrations/1708479985804-user-date-column.ts
  src/users/constants/user-status.enum.ts
  src/users/entities/user.entity.ts
  src/users/user-reports/constants/user-report-type.enum.ts
  src/users/user-reports/controllers/user-reports.controller.ts
  src/users/user-reports/entities/user-report.entity.ts
  src/users/user-reports/services/user-reports.service.ts
  src/users/user-reports/user-reports.module.ts
  src/users/user.module.ts
Labels: Setting

#256 bugfix/#251/create report api
  src/boards/dto/helpMeBoard/help-me-board.dto.ts
  src/boards/dto/mentorBoard/mentor-board.dto.ts
  src/comments/dto/help-you-comment.dto.ts
  src/config/typeorm.config.ts
  src/search/dtos/search-all-help-me-board.dto.ts
  src/users/dtos/user-info.dto.ts
Labels: Bugfix

#261 Modify/#260/네임스페이스 수정 및 정상적으로 join시에 emit
  src/chat/events/events.gateway.ts
Labels: Modify

#263 deploy(#260): console for socket
  src/chat/events/events.gateway.ts
Labels: Deploy

#257 Refactor/#253/auth
  src/auth/controllers/auth.controller.ts
  src/auth/enums/provider.enum.ts
  src/auth/interfaces/auth-service.interface.ts
  src/auth/interfaces/user-info.interface.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/common/interceptors/cookie.interceptor.ts
  src/users/repositories/user-image.repository.ts
  src/users/repositories/user.repository.ts
  src/users/services/user-image.service.ts
  src/users/services/user.service.ts
Labels: Refactor

#266 Modify/#260/modify chat namespace
  src/chat/controllers/chat.controller.ts
  src/chat/events/events.gateway.ts
  src/chat/repositories/chat.repository.ts
  src/chat/services/chat.service.ts
Labels: Modify

#267 Modify/#260/modify chat namespace
  src/chat/events/events.gateway.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/create-chat-image.decorators.ts
  src/chat/swagger-decorators/find-chats.decorator.ts
  src/chat/swagger-decorators/find-one-chat-room-by-user-id.decorator.ts
  src/chat/swagger-decorators/get-chat-unread-counts.decorator.ts
  src/chat/swagger-decorators/leave-chat-room.decorator.ts
Labels: Delete, Refactor, Doc

#258 Modify/#254/user soft delete
  src/auth/services/auth.service.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
Labels: Modify

#269 🚨 bugfix(#268): 로그인 중 토큰 저장 로직에서 발생했던 에러 해결
  src/auth/repositories/token.repository.ts
  src/auth/services/token.service.ts
Labels: Bugfix

#271 🚨 bugfix(#270): userUpdate 메서드 인수값 수정 (로그인 에러)
  src/auth/services/auth.service.ts
Labels: Bugfix

#272 ✨ feat(#259): user unique id 칼럼 추가
  src/migrations/1708659903406-add-user-unique-id-in-user-table.ts
  src/users/dtos/user-info.dto.ts
  src/users/entities/user.entity.ts
Labels: Feat

#279 Refactor/#277/create new dto remove banUserId property
  src/admins/banned-user/dtos/banned-user-error-response.dto.ts
  src/auth/services/auth.service.ts
Labels: Refactor

#276 Feat/#275/add filter for mentor review pagination
  src/boards/dto/helpMeBoard/help-me-board-page-query.dto.ts
  src/boards/dto/mentorBoard/mentor-board-page-query.dto.ts
  src/common/constants/optional-boolean-mapper.ts
  src/common/constants/query-page-size.ts
  src/common/decorators/transformer/string-to-boolean.spec.ts
  src/common/decorators/transformer/string-to-boolean.transformer.ts
  src/common/dto/page-query.dto.ts
  src/common/transformers/parse-optional-boolean.transformer.ts
  src/mentors/mentor-reviews/dtos/mentor-review-page-query-dto.ts
  src/mentors/mentor-reviews/mentor-reviews.module.ts
  src/mentors/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentors/mentor-reviews/services/mentor-reviews.service.ts
  src/mentors/mentor-reviews/swagger-decorators/create-mentor-review.decorator.ts
Labels: Feat, Modify

#274 Modify/#259/user unique
  src/auth/interfaces/user-info.interface.ts
  src/auth/services/auth.service.ts
  src/migrations/1708913292118-modify-user-default-option.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
Labels: Modify

#284 ✏️ modify(#278): user intro 엔티티에 기본값 설정 추가
  src/migrations/1709091725187-modify-user-intro-default-option.ts
  src/users/entities/user-intro.entity.ts
Labels: Modify

#285 Modify/#283/modify user ban service
  src/admins/banned-user/services/banned-users.service.ts
  src/auth/services/auth.service.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
Labels: Modify

#280 Deploy/#255/https back
  docker-compose.yml
  dockerfile
  entrypoint.sh
  nginx.conf
  src/users/services/user-badge.service.ts
Labels: Deploy

#288 deploy(#255) CI/CD 최적화
  .github/workflows/ma6-main.yml
  dockerfile
Labels: Deploy
