Repository modern-agile-team/Menbosha-back, pull requests merged in 2024-01, with the labels that each got.

#77 feat(#76): 로그아웃, 회원탈퇴 구현
  src/auth/controllers/auth.controller.ts
  src/auth/interfaces/auth-service.interface.ts
  src/auth/services/auth.service.ts
  src/auth/swagger-decorators/google-login.decorator.ts
  src/auth/swagger-decorators/google-logout.decorator.ts
  src/auth/swagger-decorators/google-unlink.decorator.ts
  src/config/swagger.ts
Labels: Feat

#81 Hotfix(#35) API-DELETE
  src/boards/repository/help.me.board.repository.ts
Labels: Bugfix

#83 Feat/#79/user 내 정보 불러오기 API 추가
  src/config/guards/jwt-access-token.guard.ts
  src/config/guards/jwt-optional.guard.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/get-my-intro.dto.ts
  src/users/dtos/get-my-profile.dto.ts
  src/users/dtos/get-user-badge.dto.ts
  src/users/dtos/user-badge.dto.ts
  src/users/dtos/user-info.dto.ts
  src/users/repositories/user-badge.repository.ts
  src/users/repositories/user-intro.repository.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-my-profile-decorator.ts
  src/users/swagger-decorators/get-my-rank-decorators.ts
  src/users/user.module.ts
Labels: Feat

#82 modify find all chat rooms with user and chat api
  src/chat/controllers/chat.controller.ts
  src/chat/dto/chat-room.dto.ts
  src/chat/dto/chat.dto.ts
  src/chat/dto/response-get-chat-rooms-pagination.dto.ts
  src/chat/repositories/chat.repository.ts
  src/chat/schemas/chats.schemas.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/get-chat-rooms-new.decorator.ts
  src/chat/swagger-decorators/get-chat-unread-counts.decorator.ts
  src/chat/swagger-decorators/get-chats.decorator.ts
  src/common/dto/pagination-response.dto.ts
Labels: Modify

#84 Feat/#74/user intro
  src/users/controllers/user.controller.ts
  src/users/dtos/create-user-intro-dto.ts
  src/users/dtos/response-user-dto.ts
  src/users/dtos/update-user-intro-dto.ts
  src/users/repositories/user-intro-repositories.ts
  src/users/repositories/user.repository.ts
  src/users/services/user-intro-service.ts
  src/users/swagger-decorators/patch-user-intro-decorator.ts
  src/users/swagger-decorators/upload-user-Intro-decorators.ts
  src/users/user.module.ts
Labels: Feat

#87 docs(#79): swagger 문서 추가
  src/users/controllers/user.controller.ts
  src/users/swagger-decorators/get-user-info.decorators.ts
Labels: Doc

#90 refactor(#89): 유저 이미지 업데이트 API 리팩토링
  src/auth/services/auth.service.ts
  src/users/controllers/user-image.controller.ts
  src/users/services/user-image.service.ts
  src/users/swagger-decorators/update-user-image.decorator.ts
Labels: Refactor

#95 Feat/#22/mentor board api
  src/boards/controllers/mentor.board.controller.ts
  src/boards/dto/mentorBoard/one.response.mentor.boards.dto.ts
  src/boards/dto/mentorBoard/response.mentor.boards.dto.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/get-page-mentor-boards-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-page-number-mentor-board-decorator.ts
  src/search/services/search.service.ts
Labels: Modify

#97 Feat/#96/category id board user
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/controllers/mentor.board.controller.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/services/help.me.board.service.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/helpMeBoard/get-board-page-number.decorator.ts
  src/boards/swagger-decorators/helpMeBoard/get-page-help-me-board.decorator.ts
  src/boards/swagger-decorators/mentorBoard/get-page-mentor-boards-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-page-number-mentor-board-decorator.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-mentor-list-decorator.ts
  src/users/swagger-decorators/get-mentor-page-decorator.ts
Labels: Modify

#100 Feat/#99/random mentor board
  src/boards/controllers/mentor.board.controller.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/get-random-mentor-boards-decorator.ts
Labels: Feat

#106 Feat/#92/user ranking 엔티티 추가 및 API 추가
  src/auth/auth.module.ts
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.ts
  src/comments/entities/help-you-comment.entity.ts
  src/config/typeorm.config.ts
  src/search/dtos/search-all-help-me-board.dto.ts
  src/total-count/controllers/total-count.controller.ts
  src/total-count/entities/total-count.entity.ts
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/total-count/total-count.module.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/user-info.dto.ts
  src/users/entities/user-ranking.entity.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user-ranking.repository.ts
  src/users/services/user-intro-service.ts
  src/users/services/user-ranking.service.ts
  src/users/user.module.ts
Labels: Feat

#109 Feat/#101/help me board pulling up
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/entities/help-me-board.entity.ts
  src/boards/services/help.me.board.service.ts
Labels: Bugfix, Modify

#110 Feat/#105/help comment api
  src/comments/controllers/comments.controller.ts
  src/comments/dto/get-all-comment-dto.ts
  src/comments/entities/help-you-comment.entity.ts
  src/comments/repository/comments.repository.ts
  src/comments/services/comments.services.ts
  src/comments/swagger-decorators/delete-comment-decorator.ts
  src/comments/swagger-decorators/get-all-comment-decorators.ts
  src/comments/swagger-decorators/patch-comment-decorators.ts
  src/comments/swagger-decorators/post-help-you-comment-decorator.ts
Labels: Feat, Modify

#103 mentor board hot post
  src/boards/boards.module.ts
  src/boards/constants/mentor-board-order-field.enum.ts
  src/boards/controllers/mentor-board-hot-posts.controller.ts
  src/boards/controllers/mentor-board-likes.controller.ts
  src/boards/dto/mentorBoard/mentor-board-for-hot-post.dto.ts
  src/boards/dto/mentorBoard/mentor-board-page-query.dto.ts
  src/boards/dto/mentorBoard/mentor-board.dto.ts
  src/boards/dto/mentorBoard/response-mentor-board-hot-post-pagination.dto.ts
  src/boards/entities/help-me-board.entity.ts
  src/boards/entities/mentor-board.entity.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/mentor-board-hot-posts.service.ts
  src/boards/services/mentor-board-like.service.ts
  src/boards/services/mentor-board-likes.service.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/find-all-hot-posts-with-pagination.decorator.ts
  src/boards/swagger-decorators/mentorBoard/get-mentor-board-likes.decorator.ts
  src/chat/controllers/chat.controller.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/create-chat-room.decorator.ts
  src/common/constants/sort-order.enum.ts
  src/common/dto/page-query.dto.ts
  src/hot-posts/constants/hot-post.token.ts
  src/hot-posts/hot-posts.module.ts
  src/hot-posts/repositories/hot-posts.repository.ts
  src/hot-posts/types/hot-post.type.ts
  src/like/likes.module.ts
  src/like/repositories/likes.repository.ts
  src/like/services/likes.service.ts
  src/search/dtos/search-all-boards-and-mentors-query.dto.ts
Labels: Feat

#111 Modify/#94/mentor_board_hot_post
  src/app.module.ts
  src/boards/boards.module.ts
  src/boards/controllers/mentor-board-hot-posts.controller.ts
  src/boards/dto/mentorBoard/mentor-board-page-query.dto.ts
  src/boards/services/mentor-board-hot-posts.service.ts
  src/category/category.module.ts
  src/category/dto/category-list.dto.ts
  src/category/repositories/category.repository.ts
  src/category/services/category.service.ts
  src/common/dto/validators/is-positive-int.decorator.ts
Labels: Modify

#113 Feat/#43/mentor list api
  src/users/controllers/user.controller.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-mentor-list-decorator.ts
Labels: Modify

#118 modify(#79): 내 프로필 불러오기 API 리턴값 수정
  src/users/dtos/get-my-profile.dto.ts
  src/users/dtos/user-info.dto.ts
Labels: Modify

#115 Feat/#92/user ranking 멘토 랭크 업데이트 로직 구현
  src/auth/controllers/auth.controller.ts
  src/total-count/dtos/update-counting.dto.ts
  src/total-count/entities/total-count.entity.ts
  src/total-count/repositories/total-count.repository.ts
  src/total-count/services/total-count.service.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/dtos/response-user-ranking.dto.ts
  src/users/entities/user-ranking.entity.ts
  src/users/repositories/user-ranking.repository.ts
  src/users/services/user-ranking.service.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-total-ranking.decorator.ts
Labels: Feat

#119 병합 충돌 머지
  src/users/controllers/user.controller.ts
  src/users/repositories/user-badge.repository.ts
  src/users/services/user-badge.service.ts
Labels: Setting

#120 modify(#92): user_ranking 엔티티 칼럼 이름 수정
  src/users/entities/user-ranking.entity.ts
Labels: Modify

#121 hotfix(#92): 머지 버그 수정
  src/users/controllers/user.controller.ts
Labels: Bugfix

#122 Delete/#116/remove unused chat api
  src/chat/controllers/chat.controller.ts
  src/chat/dto/aggregate-chat-room-for-chats.dto.ts
  src/chat/dto/chat-rooms-without-chats-item.dto.ts
  src/chat/dto/response-find-chat-rooms-pagination.dto.ts
  src/chat/dto/response-find-chat-rooms.dto.ts
  src/chat/repositories/chat.repository.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/create-chat-room.decorator.ts
  src/chat/swagger-decorators/find-chat-notification-Sse.decorator.ts
  src/chat/swagger-decorators/find-chat-rooms.decorator.ts
  src/chat/swagger-decorators/find-chats.decorator.ts
  src/chat/swagger-decorators/find-one-chat-room-by-user-id.decorator.ts
  src/chat/swagger-decorators/find-one-chat-room.decorator.ts
  src/chat/swagger-decorators/get-chat-rooms.decorator.ts
  src/users/dtos/chat-user.dto.ts
Labels: Delete, Modify

#124 Refactor/#123/token error handling
  src/auth/services/token.service.ts
  src/auth/swagger-decorators/delete-account.decorator.ts
  src/auth/swagger-decorators/google-logout.decorator.ts
  src/auth/swagger-decorators/google-unlink.decorator.ts
  src/auth/swagger-decorators/kakao-logout.decorator.ts
  src/auth/swagger-decorators/kakao-unlink.decorator.ts
  src/auth/swagger-decorators/naver-logout.decorator.ts
  src/auth/swagger-decorators/naver-unlink.decorator.ts
  src/auth/swagger-decorators/new-access-token.decorator.ts
  src/users/swagger-decorators/get-my-profile-decorator.ts
  src/users/swagger-decorators/patch-user-intro-decorator.ts
  src/users/swagger-decorators/update-user-image.decorator.ts
  src/users/swagger-decorators/upload-user-Intro-decorators.ts
Labels: Refactor

#126 Feat/#125/modify and create table
  migrations/1705725351584-modify-user-review-table.ts
  package.json
  src/config/typeorm.config.ts
  src/users/entities/mentor-review-checklist.entity.ts
  src/users/entities/mentor-review.entity.ts
  src/users/entities/transformers/boolean.transformer.ts
  src/users/entities/user-review.entity.ts
  src/users/entities/user.entity.ts
Labels: Feat, Modify

#128 Feat/#127/create review api
  src/app.module.ts
  src/boards/constants/mentor-board-order-field.enum.ts
  src/config/typeorm.config.ts
  src/mentors/constants/mentor-review-order-field.enum.ts
  src/mentors/controllers/mentors.controller.ts
  src/mentors/dtos/create-mentor-review-checklist-request-body.dto.ts
  src/mentors/dtos/create-mentor-review-request-body.dto.ts
  src/mentors/dtos/mentor-review-checklist.dto.ts
  src/mentors/dtos/mentor-review-page-query-dto.ts
  src/mentors/dtos/mentor-review.dto.ts
  src/mentors/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/dtos/mentor-reviews-pagination-response.dto.ts
  src/mentors/dtos/patch-update-mentor-review.dto.ts
  src/mentors/entities/mentor-review-checklist.entity.ts
  src/mentors/entities/mentor-review.entity.ts
  src/mentors/entities/transformers/boolean.transformer.ts
  src/mentors/mentors.module.ts
  src/mentors/repositories/mentors.repository.ts
  src/mentors/services/mentors.service.ts
  src/mentors/swagger-decorators/create-mentor-review.decorator.ts
  src/mentors/swagger-decorators/find-mentor-reviews.decorator.ts
  src/mentors/swagger-decorators/find-one-mentor-review.decorator.ts
  src/mentors/swagger-decorators/patch-update-mentor-review.decorator.ts
  src/mentors/swagger-decorators/remove-mentor-review.decorator.ts
  src/migrations/1705814513284-modify-mentor-review-nullable.ts
  src/migrations/1705836905872-mentor-review-soft-delete.ts
  src/migrations/1705843495576-mentor-review-checklist-soft-delete.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user.repository.ts
  src/users/services/user.service.ts
Labels: Feat

#129 Feat/#101/help me board pulling up
  src/boards/controllers/help.me.boards.controller.ts
  src/boards/repository/help.me.board.repository.ts
  src/boards/services/help.me.board.service.ts
  src/boards/swagger-decorators/helpMeBoard/get-pulling-up-help-me-board-decorator.ts
Labels: Modify

#130 Feat/#99/random mentor board
  src/boards/controllers/mentor.board.controller.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/get-random-mentor-boards-decorator.ts
Labels: Modify

#133 Feat/#92/user ranking total-ranking API return 값 수정
  src/migrations/1705996137498-userRanking.ts
  src/migrations/1706015414954-modify-total-count-entity-name.ts
  src/total-count/entities/total-count.entity.ts
  src/total-count/repositories/total-count.repository.ts
  src/users/dtos/response-user-ranking.dto.ts
  src/users/dtos/user-info.dto.ts
  src/users/entities/user-ranking.entity.ts
  src/users/entities/user.entity.ts
  src/users/repositories/user-ranking.repository.ts
  src/users/services/user-ranking.service.ts
Labels: Modify

#137 Feat/#43/mento list api
  src/boards/boards.module.ts
  src/boards/dto/mentorBoard/one.response.mentor.boards.dto.ts
  src/boards/dto/mentorBoard/response.mentor.boards.dto.ts
  src/boards/repository/mentor.board.likes.repository.ts
  src/boards/repository/mentor.boards.repository.ts
  src/boards/services/mentor.board.service.ts
  src/search/controllers/search.controller.ts
  src/search/services/search.service.ts
Labels: Modify

#139 Feat/#43/mento list api
  src/boards/dto/mentorBoard/one.response.mentor.boards.dto.ts
  src/boards/dto/mentorBoard/response.mentor.boards.dto.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/get-one-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-page-mentor-boards-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-random-mentor-boards-decorator.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-mentor-list-decorator.ts
Labels: Modify

#140 feat(#92): swagger authorization 기능 추가
  src/auth/controllers/auth.controller.ts
  src/auth/swagger-decorators/delete-account.decorator.ts
  src/auth/swagger-decorators/google-logout.decorator.ts
  src/auth/swagger-decorators/google-unlink.decorator.ts
  src/auth/swagger-decorators/kakao-logout.decorator.ts
  src/auth/swagger-decorators/kakao-unlink.decorator.ts
  src/auth/swagger-decorators/naver-logout.decorator.ts
  src/auth/swagger-decorators/naver-unlink.decorator.ts
  src/auth/swagger-decorators/new-access-token.decorator.ts
  src/config/guards/jwt-access-token.guard.ts
  src/config/guards/jwt-refresh-token.guard.ts
  src/config/swagger.ts
  src/main.ts
  src/total-count/controllers/total-count.controller.ts
  src/total-count/swagger-decorators/counting.decorator.ts
  src/users/controllers/user-image.controller.ts
  src/users/controllers/user.controller.ts
  src/users/swagger-decorators/get-my-info-with-owner-decorator.ts
  src/users/swagger-decorators/get-my-profile-decorator.ts
  src/users/swagger-decorators/patch-user-intro-decorator.ts
  src/users/swagger-decorators/update-user-image.decorator.ts
  src/users/swagger-decorators/upload-user-Intro-decorators.ts
  tsconfig.json
Labels: Feat

#134 Modify/#131/modify chat logic
  src/chat/controllers/chat.controller.ts
  src/chat/dto/aggregate-chat-rooms.dto.ts
  src/chat/services/chat.service.ts
  src/chat/swagger-decorators/create-chat-image.decorators.ts
  src/chat/swagger-decorators/create-chat-room.decorator.ts
  src/chat/swagger-decorators/delete-chat.decorator.ts
  src/chat/swagger-decorators/find-chat-notification-Sse.decorator.ts
  src/chat/swagger-decorators/find-chat-rooms.decorator.ts
  src/chat/swagger-decorators/find-chats.decorator.ts
  src/chat/swagger-decorators/leave-chat-room.decorator.ts
Labels: Modify

#135 Bugfix/#132/bugfix in hot post logic
  src/boards/dto/mentorBoard/mentor-board-for-hot-post.dto.ts
  src/boards/services/mentor-board-hot-posts.service.ts
  src/boards/swagger-decorators/mentorBoard/find-all-hot-posts-with-pagination.decorator.ts
Labels: Bugfix, Doc

#142 doc/#141/modify swagger api docs
  src/boards/swagger-decorators/mentorBoard/create-mentor-board-like.decorator.ts
  src/boards/swagger-decorators/mentorBoard/delete-mentor-board-like.decorator.ts
  src/chat/swagger-decorators/create-chat-image.decorators.ts
  src/chat/swagger-decorators/create-chat-room.decorator.ts
  src/chat/swagger-decorators/delete-chat.decorator.ts
  src/chat/swagger-decorators/find-chat-notification-Sse.decorator.ts
  src/chat/swagger-decorators/find-chat-rooms.decorator.ts
  src/chat/swagger-decorators/find-chats.decorator.ts
  src/chat/swagger-decorators/find-one-chat-room-by-user-id.decorator.ts
  src/chat/swagger-decorators/leave-chat-room.decorator.ts
  src/mentors/swagger-decorators/create-mentor-review.decorator.ts
  src/mentors/swagger-decorators/patch-update-mentor-review.decorator.ts
  src/mentors/swagger-decorators/remove-mentor-review.decorator.ts
Labels: Refactor, Doc

#143 Feat/#138/user user-intro 엔티티 수정 및 API 수정
  src/auth/controllers/auth.controller.ts
  src/config/guards/jwt-access-token.guard.ts
  src/config/guards/jwt-optional.guard.ts
  src/config/guards/jwt-refresh-token.guard.ts
  src/mentors/dtos/mentor-reviews-item-response.dto.ts
  src/mentors/repositories/mentors.repository.ts
  src/migrations/1706078088801-modify-user-intro-entity.ts
  src/search/dtos/search-all-mentor.dto.ts
  src/users/controllers/user.controller.ts
  src/users/dtos/create-user-intro-dto.ts
  src/users/dtos/get-my-intro.dto.ts
  src/users/dtos/page-by-mentor-list-response-dto.ts
  src/users/dtos/response-user-dto.ts
  src/users/dtos/update-user-intro-dto.ts
  src/users/entities/user-intro.entity.ts
  src/users/repositories/user-intro.repository.ts
  src/users/repositories/user-ranking.repository.ts
  src/users/services/user-intro-service.ts
  src/users/services/user.service.ts
  src/users/swagger-decorators/get-user-info.decorators.ts
  src/users/swagger-decorators/patch-user-intro-decorator.ts
Labels: Modify

#145 modify/#144/body substring
  src/boards/dto/mentorBoard/mentor-board-for-hot-post.dto.ts
  src/index.html
Labels: Modify

#149 Feat/#43/mento list api
  src/boards/dto/mentorBoard/one.response.mentor.boards.dto.ts
  src/boards/repository/mentor.board.likes.repository.ts
  src/boards/services/mentor.board.service.ts
  src/boards/swagger-decorators/mentorBoard/get-one-mentor-board-decorators.ts
Labels: Modify

#148 Feat/#138/user 로그인 시 firstLogin 리턴값 추가, swagger 문서 수정
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.ts
  src/auth/swagger-decorators/delete-account.decorator.ts
  src/auth/swagger-decorators/google-login.decorator.ts
  src/auth/swagger-decorators/google-logout.decorator.ts
  src/auth/swagger-decorators/google-unlink.decorator.ts
  src/auth/swagger-decorators/kakao-login.decorator.ts
  src/auth/swagger-decorators/kakao-logout.decorator.ts
  src/auth/swagger-decorators/kakao-unlink.decorator.ts
  src/auth/swagger-decorators/naver-login.decorator.ts
  src/auth/swagger-decorators/naver-logout.decorator.ts
  src/auth/swagger-decorators/naver-unlink.decorator.ts
  src/auth/swagger-decorators/new-access-token.decorator.ts
  src/total-count/controllers/total-count.controller.ts
  src/total-count/swagger-decorators/counting.decorator.ts
  src/users/controllers/user.controller.ts
  src/users/swagger-decorators/get-my-info-with-owner-decorator.ts
  src/users/swagger-decorators/get-my-profile-decorator.ts
  src/users/swagger-decorators/get-my-rank-decorators.ts
  src/users/swagger-decorators/patch-user-intro-decorator.ts
  src/users/swagger-decorators/upload-user-Intro-decorators.ts
Labels: Doc, Modify

#151 fix/#146/modify deprecated method
  src/like/repositories/likes.repository.ts
Labels: Modify

#152 hotfix(#146): modify error
  src/like/services/likes.service.ts
Labels: Bugfix

#155 Refactor/#154/api bearer auth access tok
  src/boards/swagger-decorators/helpMeBoard/add-help-me-board-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/add-help-me-board-images-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/delete-help-me-board-decorator.ts
  src/boards/swagger-decorators/helpMeBoard/get-one-help-me-board.dto.ts
  src/boards/swagger-decorators/helpMeBoard/patch-help-me-board-images-decorators.ts
  src/boards/swagger-decorators/helpMeBoard/patch-help-me-board.decorator.ts
  src/boards/swagger-decorators/helpMeBoard/pulling-up-help-me-board.decorator.ts
  src/boards/swagger-decorators/mentorBoard/add-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/add-mentor-board-images-decorator.ts
  src/boards/swagger-decorators/mentorBoard/delete-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/get-one-mentor-board-decorators.ts
  src/boards/swagger-decorators/mentorBoard/patch-mentor-board-decorators.ts
  src/comments/swagger-decorators/delete-comment-decorator.ts
  src/comments/swagger-decorators/get-all-comment-decorators.ts
  src/comments/swagger-decorators/post-help-you-comment-decorator.ts
Labels: Refactor

#153 Modify/#146/modify return type
  src/search/controllers/search.controller.ts
  src/search/services/search.service.ts
  src/search/swagger-decorators/search-boards-by-body.decorator.ts
  src/search/swagger-decorators/search-boards-by-head-or-body-or-user-name.decorator.ts
  src/search/swagger-decorators/search-boards-by-head.decorator.ts
  src/search/swagger-decorators/search-boards-by-user-name.decorator.ts
  src/search/swagger-decorators/search-users-by-user-name.decorato.ts
Labels: Delete

#158 Modify/#147/mongoose transaction
  src/chat/dto/chat-room.dto.ts
  src/chat/dto/chat.dto.ts
  src/chat/schemas/chat-rooms.schemas.ts
  src/chat/services/chat.service.ts
Labels: Modify

#163 doc/#162/create async api docs
  src/main.ts
Labels: Doc

#159 Feat/#138/user update-counting dto 칼럼 이름에 맞춰서 수정
  src/total-count/dtos/update-counting.dto.ts
  src/total-count/enums/type.enum.ts
  src/total-count/services/total-count.service.ts
  src/users/controllers/user.controller.ts
  src/users/services/user-badge.service.ts
  src/users/user.module.ts
Labels: Modify

#161 modify(#160): 리프레시 토큰 에러 핸들링 수정
  src/auth/services/token.service.ts
  src/auth/swagger-decorators/new-access-token.decorator.ts
Labels: Modify

#165 modify(#160): 토큰이 제공되지 않았을 때 가드에서 막기
  src/config/guards/jwt-access-token.guard.ts
  src/config/guards/jwt-refresh-token.guard.ts
Labels: Modify

#166 modify(#160): 토큰 에러 핸들링 추가
  src/auth/services/token.service.ts
Labels: Modify

#164 feat(#92): user-ranking entity 수정, 1시간마다 유저 랭킹 테이블에 유저정보 업데이트
  src/migrations/1706596603421-modify-user-ranking-entity.ts
  src/total-count/services/total-count.service.ts
  src/users/entities/user-ranking.entity.ts
  src/users/repositories/user-ranking.repository.ts
  src/users/services/user-ranking.service.ts
Labels: Feat, Modify

#171 deploy(#30): redis 연결시에 비밀번호 추가
  docker-compose.yml
  src/config/redis-options.constants.ts
Labels: Deploy

#173 deploy(#30): redis 연결시에 비밀번호 추가
  docker-compose.yml
Labels: Deploy

#174 Feat/#172/create checklist count ta
  src/migrations/1706687627541-CreateMentorReviewChecklistCountTable.ts
  src/migrations/__utils/util.ts
  src/total-count/entities/mentor-review-checklist-count.entity.ts
  src/users/entities/user.entity.ts
Labels: Feat

#176 Fix/#175/fix error
  src/users/dtos/user-info.dto.ts
Labels: Bugfix

#168 setting(#167): setting logger
  src/app.module.ts
  src/main.ts
  src/middlewares/logger.middleware.ts
Labels: Setting

#177 deploy(#30): redis 연결시에 비밀번호 추가
  docker-compose.yml
  src/common/redis/redis.module.ts
Labels: Bugfix

#157 Feat/#156/custom repository
  src/app.module.ts
  src/common/entity/transformers/boolean.transformer.ts
  src/config/type-orm/constants/type-orm.token.ts
  src/config/type-orm/decorators/custom-repository.decorator.ts
  src/config/type-orm/type-orm-ex.module.ts
  src/config/type-orm/typeorm.config.ts
  src/mentor-reviews/constants/mentor-review-order-field.enum.ts
  src/mentor-reviews/controllers/mentor-reviews.controller.ts
  src/mentor-reviews/dtos/create-mentor-review-checklist-request-body.dto.ts
  src/mentor-reviews/dtos/create-mentor-review-request-body.dto.ts
  src/mentor-reviews/dtos/mentor-review-checklist.dto.ts
  src/mentor-reviews/dtos/mentor-review-page-query-dto.ts
  src/mentor-reviews/dtos/mentor-review.dto.ts
  src/mentor-reviews/dtos/mentor-reviews-item-response.dto.ts
  src/mentor-reviews/dtos/mentor-reviews-pagination-response.dto.ts
  src/mentor-reviews/dtos/patch-update-mentor-review.dto.ts
  src/mentor-reviews/entities/mentor-review.entity.ts
  src/mentor-reviews/mentor-review-checklist/entities/mentor-review-checklist.entity.ts
  src/mentor-reviews/mentor-review-checklist/mentor-review-checklist.module.ts
  src/mentor-reviews/mentor-review-checklist/repositories/mentor-review-checklists.repository.ts
  src/mentor-reviews/mentor-review-checklist/services/mentor-review-checklist.service.ts
  src/mentor-reviews/mentor-reviews.module.ts
  src/mentor-reviews/repositories/mentor-review.repository.ts
  src/mentor-reviews/services/mentor-reviews.service.ts
  src/mentor-reviews/swagger-decorators/create-mentor-review.decorator.ts
  src/mentor-reviews/swagger-decorators/find-mentor-reviews.decorator.ts
  src/mentor-reviews/swagger-decorators/find-one-mentor-review.decorator.ts
  src/mentor-reviews/swagger-decorators/patch-update-mentor-review.decorator.ts
  src/mentor-reviews/swagger-decorators/remove-mentor-review.decorator.ts
  src/mentors/mentors.module.ts
  src/mentors/repositories/mentors.repository.ts
  src/mentors/services/mentors.service.ts
  src/users/entities/user.entity.ts
Labels: Setting, Feat, Modify
